# Numpy
Matlab users: https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

In [1]:
import numpy as np

# Types
https://numpy.org/devdocs/user/basics.types.html

In [44]:
np.int64(3)  # default int

3

In [43]:
np.float64(3)  # default float

3.0

In [51]:
np.uint8(256)  # out of bounds

0

In [53]:
np.uint8(255)

255

# Basic Arrays

In [62]:
# single dimension
a = np.array([1,2,3,4])

In [63]:
# multi dimension
b = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
# works like a list
a[2]

3

In [69]:
# however can be selected in two ways for multi dimension
b[2][2]
b[2, 2]  # Recommended way

11

# Array creation

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.full((3,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [71]:
np.arange(10)  # like python range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
# random int array
np.random.randint(10, size=(3,3))

array([[6, 5, 9],
       [3, 8, 5],
       [8, 7, 0]])

# Array manipulation

In [21]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
b.reshape(4,3)  # resize

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
# convert linear
b.reshape(-1)
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
# Transpose
b.transpose()
b.T  # recommended

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [79]:
b.astype(float)  # convert to float

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [80]:
b.tolist()  # convert to python list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [87]:
b[::-1]  # inverse

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [94]:
c = b.copy()

In [99]:
c[2, :] = [0, 0, 0, 0]
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

# Statistics

In [90]:
np.median(b)

6.5

In [30]:
np.mean(b)

6.5

In [41]:
np.mean(b, axis=1)

array([ 2.5,  6.5, 10.5])

In [93]:
np.max(b)

12

# API Documentation
https://numpy.org/doc/stable/reference/routines.html